[package]
name = "udp-multicast-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1"
eframe = "0.18"
socket2 = "0.4"

[dependencies.tokio]
version = "1.20"
default-features = false
features = ["macros", "net", "parking_lot", "rt", "sync"]

[profile.release]
lto = true
strip = true
